Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2019-08, with the labels that each got.

#73 Stop using travis for unit test and verify
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, size/S

#70 Upgrade to golang 1.12
  .travis.yml
  Dockerfile
Labels: cncf-cla: yes, size/XS

#77 Remove DISCLAIMER
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#75 Remove service account for node service
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#78 Bump driver version to 0.2.0
  Makefile
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS

#55 Run upstream e2e tests
  Makefile
  hack/run-e2e-test
  test/e2e/README.md
  test/e2e/e2e_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/hack/update-gomod.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#79 Add dockerignore to ignore vendor dir
  .dockerignore
Labels: approved, cncf-cla: yes, size/XS
