Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2019-07, with the labels that each got.

#47 fix namespace in csi-node clusterrole
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#48 Update to CSI v1.1.0
  go.mod
  go.sum
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#53 Replace deprecated Recycle policy with Retain
  examples/kubernetes/encryption_in_transit/README.md
  examples/kubernetes/encryption_in_transit/specs/pv.yaml
  examples/kubernetes/multiple_pods/README.md
  examples/kubernetes/multiple_pods/specs/pv.yaml
  examples/kubernetes/static_provisioning/README.md
  examples/kubernetes/static_provisioning/specs/pv.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#59 Update readme
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#61 Add linux nodeSelector to manifest.yaml
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#54 Add sanity test
  .travis.yml
  Makefile
  go.mod
  go.sum
  pkg/driver/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#62 Add liveness probe
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#65 Add example for volume path
  examples/kubernetes/volume_path/README.md
  examples/kubernetes/volume_path/specs/example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
