Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#258 Added jqmichael as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#238 Implement NodeGetVolumeStats
  cmd/main.go
  pkg/driver/driver.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/driver/vol_statter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#255 Bump chart version as appVersion was updated to 1.0.0
  helm/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#260 Correcting the helm chart imagePullSecrets variable not being used
  helm/Chart.yaml
  helm/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#266 Add E2E test flag for EFS file system ID
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#271 Add Makefile target for test e2e binary
  Makefile
  test/e2e/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/storage, size/S

#270 Handled pre-installed CSIDriver object
  helm/templates/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
