Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2020-07, with the labels that each got.

#212 Started treating the efs-utils config dir stateful and also handles the static files installed at image build time
  Dockerfile
  Makefile
  cmd/main.go
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/dev/efs_utils_config_volume.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/dev/latest_image.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  helm/templates/daemonset.yaml
  pkg/driver/driver.go
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
  pkg/driver/sanity_test.go
  pkg/driver/version.go
  pkg/driver/version_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#215 Build and push every master commit to master tag
  .github/workflows/container-image.yaml
  Makefile
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/dev/master_image.yaml
  docs/README.md
  hack/run-e2e-test
Labels: approved, cncf-cla: yes, lgtm, size/S

#216 Update efs-utils to 1.26-3.amzn2 and amazonlinux to 2.0.20200602.0
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#205 Add encryptInTransit volume attribute
  docs/README.md
  examples/kubernetes/encryption_in_transit/README.md
  examples/kubernetes/encryption_in_transit/specs/pv.yaml
  pkg/driver/node.go
  pkg/driver/node_test.go
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#218 Release v1.0.0
  CHANGELOG-1.x.md
  Makefile
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/dev/efs_utils_config_volume.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  helm/Chart.yaml
  helm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#220 Post-release v1.0.0: update CHANGELOG
  CHANGELOG-1.x.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#219 Post-release v1.0.0: update CHANGELOG
  CHANGELOG-1.x.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#221 Post-release v1.0.0: update ECR stable overlay image tags to match vanilla stable overlay
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#222 Post-release v1.0.0: update ECR stable overlay image tags to match vanilla stable overlay
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#224 Fix restart test creating pod on random, potentially wrong, node
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#231 Fix mounting /etc/amazon/efs in the node-driver-registrar container instead of the efs-plugin one
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#230 Fix mounting /etc/amazon/efs in the node-driver-registrar container instead of the efs-plugin one
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
