Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2020-12, with the labels that each got.

#272 Don't fail making mount dirs if they already exist
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#288 Added dnsPolicy and dnsConfig to helm chart
  helm/Chart.yaml
  helm/templates/daemonset.yaml
  helm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#261 Add logLevel to helm
  helm/templates/daemonset.yaml
  helm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
