Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2020-06, with the labels that each got.

#169 Upgraded CSI spec to v1.2.0
  Dockerfile
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  go.mod
  go.sum
  pkg/driver/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#174 Bump k8s dependencies to 1.17.6
  go.mod
  go.sum
  pkg/driver/mocks/mock_mount.go
  pkg/driver/mounter.go
  tester/e2e-test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#179 Persisted private key genereated by efs-util to host
  Dockerfile
  Makefile
  cmd/main.go
  deploy/kubernetes/base/node.yaml
  helm/templates/daemonset.yaml
  pkg/driver/driver.go
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
  pkg/driver/sanity_test.go
  pkg/driver/version.go
  pkg/driver/version_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#186 DRY TestNodePublishVolume
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#185 Support access points on the same file system
  examples/kubernetes/access_points/README.md
  examples/kubernetes/access_points/specs/example.yaml
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#173 Add e2e test for mounting different paths on same volume on same node
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#187 Add test for restarting/deleting driver pod affecting existing mount read/write
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#189 Fix TestNodeUnpublishVolume
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#188 Add hostNetwork: true to daemonset yamls
  deploy/kubernetes/base/node.yaml
  helm/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#195 Update dev overlay to correctly set imagePullPolicy
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/dev/latest_image.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#154 Pin dependency library versions
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#190 Refactor and extend node tests
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#164 Only publish if access type is 'mount', not 'block'
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#194 added helm repo yaml in docs folder
  docs/index.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#196 Revert "Persisted private key genereated by efs-util to host"
  Dockerfile
  Makefile
  cmd/main.go
  deploy/kubernetes/base/node.yaml
  helm/templates/daemonset.yaml
  pkg/driver/driver.go
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
  pkg/driver/sanity_test.go
  pkg/driver/version.go
  pkg/driver/version_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#202 Push image to 7 digit git sha tag instead of latest tag for master branch changes
  .github/workflows/container-image.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Move the index file to gh-pages branch
  docs/README.md
  docs/index.yaml
Labels: approved, cncf-cla: yes, size/S
