Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2020-05, with the labels that each got.

#157 Add myself to owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 Updated node.yaml to update deprecated node selectors
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#161 Bump stable overlay to 0.3.0
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#155 Bump livenessprobe and node-driver-registrar versions
  deploy/kubernetes/base/node.yaml
  helm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#162 Update stable overlay to use public images
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#165 Added client source for business tracking purpose
  Dockerfile
  Makefile
  deploy/kubernetes/base/node.yaml
  examples/kubernetes/multiple_pods/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#159 Remove hostNetwork from daemonset yamls
  deploy/kubernetes/base/node.yaml
  helm/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#170 Remove dockerfile for dev
  Dockerfile.dev
Labels: approved, cncf-cla: yes, size/S

#171 Correcting typo in access points example
  examples/kubernetes/access_points/specs/example.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#168 Doc: Access Points: Require separate file systems
  examples/kubernetes/access_points/README.md
  examples/kubernetes/access_points/specs/example.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#160 Enable e2e testing on EKS, parallelism, and make optional EFS creation/driver deployment
  go.mod
  go.sum
  test/e2e/cloud.go
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/L
