Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2020-04, with the labels that each got.

#144 Adding amd64 as nodeSelector to avoid arm64 archtectures (#143)
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#148 Move EFS tests into e2e.go so that they can be imported from elsewhere
  test/e2e/e2e.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#153 Add example for Access Points
  docs/README.md
  examples/kubernetes/access_points/README.md
  examples/kubernetes/access_points/specs/example.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
