Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2021-02, with the labels that each got.

#291 Move chart to charts directory and add workflow to publish new chart versions
  .github/workflows/cr.yaml
  .github/workflows/helm-chart-release.yaml
  .github/workflows/release.yaml
  charts/aws-efs-csi-driver/.helmignore
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/NOTES.txt
  charts/aws-efs-csi-driver/templates/_helpers.tpl
  charts/aws-efs-csi-driver/templates/controller.yaml
  charts/aws-efs-csi-driver/templates/csidriver.yaml
  charts/aws-efs-csi-driver/templates/daemonset.yaml
  charts/aws-efs-csi-driver/templates/serviceaccount.yaml
  charts/aws-efs-csi-driver/values.yaml
  docs/README.md
  tester/e2e-test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#324 helm chart: ensure that upgrades do not delete csidriver resource
  charts/aws-efs-csi-driver/templates/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#315 Release v1.1.0
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#326 Bump AL2 to 20210126.0
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#331 Release 1.1.1
  CHANGELOG-1.x.md
  Makefile
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  helm/Chart.yaml
  helm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#333 Run chart releaser action from release branches only
  .github/workflows/helm-chart-release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#327 Bump AL2 to 20210126.0
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#339 helm chart: ensure that upgrades do not delete csidriver resource
  helm/Chart.yaml
  helm/templates/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
