Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2021-04, with the labels that each got.

#389 release-1.2: Fix creation of multiple storage classes in Helm chart
  charts/aws-efs-csi-driver/templates/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#386 Fix helm chart external-provisioner RBAC not being created if serviceaccount.controller.create false
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/_helpers.tpl
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#404 release-1.2: Bump sidecar images to latest available in ecr
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#414 feat: helm add storageclass annotations
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/storageclass.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#382 Bump sidecar images to latest available in ecr
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#413 feat: add controller access point tags to helm chart
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/_helpers.tpl
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#380 Add `hostNetwork: true` on efs-csi-controller deployement.
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#422 Add `iam` mount option while deleting Access Point root directory
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#423 Add empty StorageClasses from static example
  examples/kubernetes/static_provisioning/specs/claim.yaml
  examples/kubernetes/static_provisioning/specs/pv.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#418 Add fargate support in the EFS CSI driver
  hack/update-gomock
  pkg/cloud/cloud.go
  pkg/cloud/metadata.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mocks/mock_taskmetadata.go
  pkg/cloud/task_metadata.go
  pkg/cloud/task_metadata_test.go
  pkg/driver/efs_watch_dog.go
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#425 Add x-AZ mount support for efs-csi-driver
  Dockerfile
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#426 Reduce default log level to 2
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#429 release-1.2: Release 1.2.1 and chart 1.2.3 with cherry-picked helm chart changes #380 #412 #413 #414 #426
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/_helpers.tpl
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/storageclass.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M
