Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2021-01, with the labels that each got.

#274 Introduce Controller with Create and Delete Volume capability. Adds support for Dynamic Provisioning via access points
  .travis.yml
  Makefile
  cmd/main.go
  deploy/kubernetes/base/clusterrole-provisioner.yaml
  deploy/kubernetes/base/clusterrolebinding-provisioner.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/serviceaccount-csi-controller.yaml
  deploy/kubernetes/overlays/dev/master_image.yaml
  go.mod
  go.sum
  helm/templates/_helpers.tpl
  helm/templates/controller.yaml
  helm/templates/daemonset.yaml
  helm/templates/serviceaccount.yaml
  helm/values.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/cloud/mocks/mock_efs.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/gid_allocator.go
  pkg/driver/identity.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/node.go
  pkg/driver/sanity_test.go
  test/e2e/e2e.go
  tester/e2e-test-config.yaml
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/cleanup.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/tests.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/util.go
  vendor/github.com/kubernetes-csi/csi-test/utils/grpcutil.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#292 Update chart index to have 1.0.0 as the appVersion
  index.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#286 change config dir location
  Dockerfile
  cmd/main.go
  deploy/kubernetes/base/node.yaml
  helm/templates/daemonset.yaml
  pkg/driver/config_dir.go
  pkg/driver/config_dir_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#301 Fix readme typo
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#296 Gate controller creation behind helm value
  helm/templates/_helpers.tpl
  helm/templates/controller.yaml
  helm/templates/serviceaccount.yaml
  helm/values.yaml
  tester/e2e-test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#304 Don't push to unused github registry
  .github/workflows/container-image.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#312 Release driver 1.1 and helm chart 1.1 (without dynamic provisioning)
  .travis.yml
  CHANGELOG-1.x.md
  Makefile
  cmd/main.go
  deploy/kubernetes/base/clusterrole-provisioner.yaml
  deploy/kubernetes/base/clusterrolebinding-provisioner.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/serviceaccount-csi-controller.yaml
  deploy/kubernetes/overlays/dev/master_image.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  go.mod
  go.sum
  helm/Chart.yaml
  helm/templates/_helpers.tpl
  helm/templates/controller.yaml
  helm/templates/daemonset.yaml
  helm/templates/serviceaccount.yaml
  helm/values.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/cloud/mocks/mock_efs.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/gid_allocator.go
  pkg/driver/identity.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/node.go
  pkg/driver/sanity_test.go
  test/e2e/e2e.go
  tester/e2e-test-config.yaml
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/cleanup.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/tests.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/util.go
  vendor/github.com/kubernetes-csi/csi-test/utils/grpcutil.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL
