Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2021-03, with the labels that each got.

#329 Daemonset Antiaffinity for Fargate Nodes
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#298 feat: Add option to provision StorageClasses
  charts/aws-efs-csi-driver/templates/storageclass.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#314 Link to 1.x changelog in releases
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#351 Fix leakingtapan's old email
  charts/aws-efs-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#309 Add tags to EFS resources. Update EFS Utils
  Dockerfile
  charts/aws-efs-csi-driver/templates/serviceaccount.yaml
  charts/aws-efs-csi-driver/values.yaml
  cmd/main.go
  deploy/kubernetes/base/clusterrole-provisioner.yaml
  deploy/kubernetes/base/controller.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
  test/e2e/cloud.go
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#276 Fix vulnerabilities ALAS-2020-1466 ALAS-2020-1445
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#355 Use aws-ebs-csi-driver/hack/e2e scripts for testing
  Makefile
  hack/additional-policies.yaml
  hack/e2e/.gitignore
  hack/e2e/README.md
  hack/e2e/ebs.sh
  hack/e2e/ecr.sh
  hack/e2e/helm.sh
  hack/e2e/kops.sh
  hack/e2e/run.sh
  hack/e2e/util.sh
  hack/run-e2e-test
  hack/values.yaml
  test/e2e/e2e.go
  tester/e2e-test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#297 Add documentation and examples for dynamic provisioning
  docs/README.md
  docs/iam-policy-example.json
  examples/kubernetes/dynamic_provisioning/README.md
  examples/kubernetes/dynamic_provisioning/specs/pod.yaml
  examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#337 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#306 generating kustomize from helm
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#365 Update compatibility matrix to show master and 1.2.x will require 1.17+
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#364 helm chart clean up: Remove hardcoded kube-system, set controller default true, generate kustomize from helm, bump sidecars
  Makefile
  charts/aws-efs-csi-driver/templates/NOTES.txt
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/clusterrolebinding-provisioner.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  deploy/kubernetes/base/csidriver.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/base/serviceaccount-csi-controller.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#366 Bump efs-utils version
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#368 Release v1.2.0
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#371 Use ECR sidecars by default in helm and kustomize instead of gcr
  Makefile
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#369 Remove helm chart step from release github workflow
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#370 Release v1.2.0
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#373 Don't exit script prematurely if test fails
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#372 Update ReadMe file
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#377 Release 1.2
  .github/workflows/release.yaml
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/_helpers.tpl
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/values.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#384 Revert efs-utils to 1.28.2
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#383 Don't exit script prematurely if test fails
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#385 Revert efs-utils to 1.28.2
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#388 Fix creation of multiple storage classes in Helm chart
  charts/aws-efs-csi-driver/templates/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
