Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2021-09, with the labels that each got.

#546 Release helm-chart v2.1.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#550 [release-1.3] Update ecr kustomize overlay to pull sidecars from private ecr, not public
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#548 Fix block provisioning
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: kind/bug, approved, size/M, lgtm, cncf-cla: yes

#549 Update ecr kustomize overlay to pull sidecars from private ecr, not public
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#554 Fail individual test cases if no file system id instead of preemptively
  test/e2e/README.md
  test/e2e/e2e.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#551 Release v1.3.4 and helm-chart v2.1.6
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#552 Feature/allow health ports to be configured
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#557 Release helm chart v2.1.6
  charts/aws-efs-csi-driver/Chart.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#558 [release-1.3] Feature/allow health ports to be configured
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes
