Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2021-06, with the labels that each got.

#464 Helm chart: fix reclaimPolicy and volumeBindingMode
  charts/aws-efs-csi-driver/templates/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#448 Update access point root directory name to use PV name
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#466 release-1.2: fix: use base value, not a nested value & Bump helm chart to 2.0.1
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#470 Add support for cross account mount
  Dockerfile
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/cloud/mocks/mock_efs.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#477 Add documentation and examples for cross-account mount
  docs/README.md
  examples/kubernetes/cross_account_mount/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#479 Release v1.3.0
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#480 Release v1.3.0 changes to master
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#483 Clean up unnecessary resources after installation in docker file
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#487 Fixed the error message
  docs/README.md
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#488 Update cross account mount example with specs and add missing setup step
  examples/kubernetes/cross_account_mount/README.md
  examples/kubernetes/cross_account_mount/iam-policy-examples/cross-account-assume-policy-example.json
  examples/kubernetes/cross_account_mount/iam-policy-examples/describe-mount-target-example.json
  examples/kubernetes/cross_account_mount/iam-policy-examples/node-deamonset-iam-policy-example.json
  examples/kubernetes/cross_account_mount/iam-policy-examples/trust-relationship-example.json
  examples/kubernetes/cross_account_mount/specs/pod.yaml
  examples/kubernetes/cross_account_mount/specs/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#492 Release v1.3.1
  CHANGELOG-1.x.md
  Dockerfile
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  examples/kubernetes/cross_account_mount/README.md
  examples/kubernetes/cross_account_mount/iam-policy-examples/cross-account-assume-policy-example.json
  examples/kubernetes/cross_account_mount/iam-policy-examples/describe-mount-target-example.json
  examples/kubernetes/cross_account_mount/iam-policy-examples/node-deamonset-iam-policy-example.json
  examples/kubernetes/cross_account_mount/iam-policy-examples/trust-relationship-example.json
  examples/kubernetes/cross_account_mount/specs/pod.yaml
  examples/kubernetes/cross_account_mount/specs/storageclass.yaml
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#493 Release v1.3.1 updates to master
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#494 Added extraCreateMetadata to the chart
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#500 Release v1.3.2
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  examples/kubernetes/cross_account_mount/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#501 Add v1.3.2 changes to master
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  examples/kubernetes/cross_account_mount/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M
