Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#528 release-1.3: Fix node-serviceaccount.yaml missing from kustomize
  deploy/kubernetes/base/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#527 Fix node-serviceaccount.yaml missing from kustomize
  deploy/kubernetes/base/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#530 Release v1.3.3
  CHANGELOG-1.x.md
  Dockerfile
  Makefile
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#531 Update kustomize and helm for driver version 1.3.3, helm version 2.1.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#532 Release v1.3.3
  CHANGELOG-1.x.md
  Dockerfile
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, size/M, lgtm, cncf-cla: yes

#534 Fix 1.3.3 changelog mentioning fix that's only in master branch
  CHANGELOG-1.x.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#535 release-1.3: Fix 1.3.3 changelog mentioning fix that's only in master branch
  CHANGELOG-1.x.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#544 [release-1.3] cherry-pick: Only reap zombie stunnel processes
  go.mod
  go.sum
  hack/values.yaml
  pkg/driver/driver.go
  pkg/driver/reaper.go
  vendor/github.com/mitchellh/go-ps/.gitignore
  vendor/github.com/mitchellh/go-ps/.travis.yml
  vendor/github.com/mitchellh/go-ps/LICENSE.md
  vendor/github.com/mitchellh/go-ps/README.md
  vendor/github.com/mitchellh/go-ps/Vagrantfile
  vendor/github.com/mitchellh/go-ps/process.go
  vendor/github.com/mitchellh/go-ps/process_darwin.go
  vendor/github.com/mitchellh/go-ps/process_freebsd.go
  vendor/github.com/mitchellh/go-ps/process_linux.go
  vendor/github.com/mitchellh/go-ps/process_solaris.go
  vendor/github.com/mitchellh/go-ps/process_unix.go
  vendor/github.com/mitchellh/go-ps/process_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#545 [release-1.3] Release v1.3.4
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes
