Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2021-05, with the labels that each got.

#438 release-1.2: Change controller port 9808->9909 to avoid node/ebs conflict
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  deploy/kubernetes/base/controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#439 release-1.2: Release chart 1.2.4
  charts/aws-efs-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#447 Add kbasv as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#442 Install efs-utils from github
  Dockerfile
  pkg/driver/efs_watch_dog.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#435 Create a new AWS session with the region
  pkg/cloud/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#430 Release 1.2.1
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#431 release-1.2: Bump ecr overlay tag to v1.2.1
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#437 Change controller port 9808->9909 to avoid node/ebs conflict
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  deploy/kubernetes/base/controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#406 Helm chart: make more fields configurable for the deployment, daemonset and storage class
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/_helpers.tpl
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/templates/csidriver.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/templates/storageclass.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#458 release-1.2: Helm chart 2.0.0 with changelog
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/_helpers.tpl
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/templates/csidriver.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/templates/storageclass.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
