Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2022-09, with the labels that each got.

#762 Revise awscredsuri validation to prefix check
  pkg/driver/node.go
Labels: approved, lgtm, size/XS, cncf-cla: yes

#710 EFS-CSI pod impersonation implementation
  charts/aws-efs-csi-driver/templates/csidriver.yaml
  charts/aws-efs-csi-driver/templates/node-serviceaccount.yaml
  charts/aws-efs-csi-driver/values.yaml
  cmd/main.go
  deploy/kubernetes/base/controller-serviceaccount.yaml
  deploy/kubernetes/base/csidriver.yaml
  deploy/kubernetes/base/node-serviceaccount.yaml
  examples/kubernetes/pod_iam_impersonation/README.md
  examples/kubernetes/pod_iam_impersonation/specs/example.yaml
  pkg/driver/driver.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#767 Pre-release of v1.4.1
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
  pkg/driver/config_dir.go
  pkg/driver/efs_watch_dog.go
  pkg/driver/gid_allocator.go
  pkg/driver/node.go
  pkg/driver/version.go
  pkg/driver/version_test.go
  pkg/driver/vol_statter.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#768 Post release PR of v1.4.1
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#770 revise helm chart version
  charts/aws-efs-csi-driver/Chart.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#771 Master branch update
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#777 Revert "EFS-CSI pod impersonation implementation"
  charts/aws-efs-csi-driver/templates/csidriver.yaml
  charts/aws-efs-csi-driver/templates/node-serviceaccount.yaml
  charts/aws-efs-csi-driver/values.yaml
  cmd/main.go
  deploy/kubernetes/base/controller-serviceaccount.yaml
  deploy/kubernetes/base/csidriver.yaml
  deploy/kubernetes/base/node-serviceaccount.yaml
  examples/kubernetes/pod_iam_impersonation/README.md
  examples/kubernetes/pod_iam_impersonation/specs/example.yaml
  pkg/driver/driver.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes

#778 Pre-release of v1.4.2
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes
