Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#804 Update deprecated NodeSelector
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: approved, size/XS, cncf-cla: yes

#805 Add #743 to changelog
  CHANGELOG-1.x.md
Labels: approved, size/XS, cncf-cla: yes

#810 Post release update to v1.4 branch (v1.4.3)
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#811 Post release update to master branch (v1.4.3)
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, size/M, cncf-cla: yes

#792 Update node-daemonset.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: ok-to-test, size/XS, cncf-cla: yes

#815 reverted the efs-utils version to v1.33.4 pre-release v1.4.4
  CHANGELOG-1.x.md
  Dockerfile
  Makefile
  docs/README.md
Labels: ok-to-test, size/M, lgtm, cncf-cla: yes

#817 Reverting efs-utils version
  CHANGELOG-1.x.md
  Dockerfile
  Makefile
  docs/README.md
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes

#825 reverted the efs-utils version back to v1.33.4 (post-release v1.4.4..)
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, lgtm, size/S, cncf-cla: yes

#824 reverted the efs-utils version back to v1.33.4 (post-release v1.4.4..)
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, lgtm, size/S, cncf-cla: yes

#827 upgraded the k8s version to 1.22.3 Pre-release
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/events.go
  vendor/k8s.io/kubernetes/test/e2e/storage/framework/snapshot_resource.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volumemode.go
  vendor/modules.txt
Labels: ok-to-test, lgtm, size/L, cncf-cla: yes

#826 upgrade to k8s.io/kubernetes v1.22.3 Pre-release
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/events.go
  vendor/k8s.io/kubernetes/test/e2e/storage/framework/snapshot_resource.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volumemode.go
  vendor/modules.txt
Labels: ok-to-test, lgtm, size/L, cncf-cla: yes

#829 upgraded the k8s version to 1.22.3 && Post-release PR to v1.4.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, size/S, cncf-cla: yes

#828 upgraded the k8s version to 1.22.3 && Post-release PR to v1.4.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, size/S, cncf-cla: yes

#834 Pre-release v1.4.6
  CHANGELOG-1.x.md
  Dockerfile
  Makefile
  docs/README.md
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes

#833 Pre-release v1.4.6
  CHANGELOG-1.x.md
  Dockerfile
  Makefile
  docs/README.md
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes

#836 pre-release Changes in git command to pull latest version of utils 1.…
  Dockerfile
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes

#835 Changes in git command to pull latest version of utils to 1.34.2
  Dockerfile
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes
