Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2022-12, with the labels that each got.

#837 Post release of v1.4.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#838 Post release of v1.4.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#839 Modify example IAM policy
  docs/README.md
  examples/kubernetes/cross_account_mount/iam-policy-examples/describe-mount-target-example.json
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes

#843 Updated efs-utils to v1.34.3 && new release for efs-csi-driver v1.4.7
  CHANGELOG-1.x.md
  Dockerfile
  Makefile
  docs/README.md
Labels: ok-to-test, size/XS, cncf-cla: yes

#847 Modify example IAM policy
  CHANGELOG-1.x.md
  examples/kubernetes/cross_account_mount/iam-policy-examples/describe-mount-target-example.json
Labels: ok-to-test, size/XS, cncf-cla: yes

#848 Post release of v1.4.7
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, size/S, cncf-cla: yes

#849 Post release of v1.4.7
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#840 Bumps sidecars to 1.23
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#853 Pre-release for v1.4.8
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#855 Post release of v1.4.8 - master branch
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#858 Update README to use release-1.4
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#857 Update to use release-1.4
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#859 Update README for driver upgrade
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#860 Update README for updating driver
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#861 Updated README.md for the broken link and updated Kubernetes version Compabil…
  docs/README.md
Labels: ok-to-test, size/S, cncf-cla: yes

#862 Updated README.md (Kubernetes Version Compability Matrix.)
  docs/README.md
Labels: ok-to-test, size/S, cncf-cla: yes
