Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#782 Release-1.4 : post-release files updated
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, lgtm, size/S, cncf-cla: yes

#788 Post release master update v-1.4.2
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: ok-to-test, lgtm, size/S, cncf-cla: yes

#789 CHANGELOG UPDATED
  CHANGELOG-1.x.md
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes

#743 Update deprecated NodeSelector
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes
