Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2022-04, with the labels that each got.

#657 Go 1.18: go get -> go install
  hack/e2e/run.sh
Labels: approved, lgtm, size/XS, cncf-cla: yes

#656 Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, cncf-cla: yes

#658 [release-1.3] Go 1.18: go get -> go install
  hack/e2e/run.sh
Labels: approved, lgtm, size/XS, cncf-cla: yes

#647 URGENT / Docs: Fixing IAM policy example, missing required permissions
  docs/iam-policy-example.json
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#659 Add release changelog auto-generation script
  hack/release
Labels: approved, lgtm, size/L, cncf-cla: yes

#661 [release-1.3] Revise to add new params in efs-utils config rendering template
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#654 [release-1.3] Add release changelog auto-generatoin script
  hack/release
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#663 Revise to add new params in efs-utils config rendering template
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#655 changelog/readme/makefile udpate for v1.3.7 release
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#666 Revise utils tag number
  CHANGELOG-1.x.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#665 Post-release version(v1.3.7) update
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#674 Disable getting all secrets from ns by default
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#676 Followup PR for PR674
  deploy/kubernetes/base/controller-serviceaccount.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#677 Disable secrets sharing cross all namespace
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#680 Upgrade to v1.22.2 to mitigated CVE
  go.mod
  go.sum
  hack/update-gomock
  vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE
  vendor/k8s.io/apimachinery/third_party/forked/golang/PATENTS
  vendor/k8s.io/utils/lru/lru.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#675 Pre-release notes for v1.3.8
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
  examples/kubernetes/cross_account_mount/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#679 Post-release of v1.3.8 - master branch update
  CHANGELOG-1.x.md
  Makefile
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes
