Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-07, with the labels that each got.

#1058 Updated the security context parameter of the efs-plugin container
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  deploy/kubernetes/base/controller-deployment.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1061 Pre-release PR of v1.5.8
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1062 Post-release PR of v1.5.8
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1063 Post-release PR of v1.5.8
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1051 Merged information from EKS User Guide
  docs/README.md
  docs/efs-create-filesystem.md
  docs/iam-policy-create.md
  examples/kubernetes/dynamic_provisioning/README.md
  examples/kubernetes/multiple_pods/README.md
Labels: ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#1071 Remove usage of 'echo' from log collector script
  troubleshooting/log_collector.py
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1080 Remove usage of 'echo' from log collector script
  troubleshooting/log_collector.py
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1082 Pre-release PR of v1.5.9
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1081 Pre-release PR of v1.5.9
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes
