Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-06, with the labels that each got.

#1030 Bump the helm version to v2.4.5 to avoid losing track of state files …
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1031 Bump the helm version to v2.4.5 to avoid losing track of state files …
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1027 Validate fstype on CreateVolume, but not NodePublishVolume
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#1018 Test case to make sure that side-car images are located in Private ECR repository
  hack/e2e/run.sh
Labels: approved, size/M, lgtm, cncf-cla: yes

#1036 Validate fstype on CreateVolume, but not NodePublishVolume
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#1038 Test case to make sure that side-car images are located in Private ECR repository
  hack/e2e/run.sh
Labels: approved, size/M, lgtm, cncf-cla: yes

#1037 Upgraded golang to 1.20
  Dockerfile
  go.mod
  go.sum
Labels: approved, lgtm, size/L, cncf-cla: yes

#1039 Pre-release of v1.5.7
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1040 Pre-release of v1.5.7
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1044 Post-release PR of v1.5.7
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes
