Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#1161 Bump the side-cars to the latest
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1212 Pre-release for v1.7.2
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1213 Pre-release for v1.7.2
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1214 Update README for tags option which should be placed under controller
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1200 Add seanzatzdev-amazon OWNERS
  OWNERS
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1223 Edit file paths in provisioning.go to fix failing e2e test
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
Labels: approved, lgtm, size/S, cncf-cla: yes
