Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#1117 Add unit test - subpath pattern, repeated elements
  pkg/driver/controller_test.go
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#1118 Update manifest paths in aws-efs-csi-driver/vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1124 Add CSI_NODE_NAME to node Daemonset
  deploy/kubernetes/base/node-daemonset.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1120 Add e2e test for dynamic provisioning
  test/e2e/e2e.go
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#1137 Move to new s3 bucket
  hack/e2e/run.sh
  hack/kops-patch.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1129 Remove old TravisCI config file
  .travis.yml
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1133 Fix ensureUniqueDirectory paramater at docs
  examples/kubernetes/dynamic_provisioning/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1135 Increased the AccessPoint MAX limit from 120 to 1000
  pkg/driver/controller_test.go
  pkg/driver/gid_allocator.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1130 Add hostnetwork back to Node Daemonset
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1026 Reusing Access Points
  docs/README.md
  examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/mocks/mock_cloud.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1142 Cherry-picking commits to release-1.7 branch
  .travis.yml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  docs/README.md
  examples/kubernetes/dynamic_provisioning/README.md
  examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml
  go.mod
  go.sum
  hack/e2e/run.sh
  hack/kops-patch.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/gid_allocator.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/sanity_test.go
  test/e2e/e2e.go
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/PATENTS
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
  vendor/modules.txt
Labels: ok-to-test, approved, lgtm, size/XXL, cncf-cla: yes

#1145 post-release PR for v1.7.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1146 post-release PR for v1.7.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1158 Updating README for 'noresvport' mount option
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes
