Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-08, with the labels that each got.

#1084 Post-release PR of v1.5.9
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1088 Update reading/writing without interruption after pod restart e2e test
  Dockerfile
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/templates/node-serviceaccount.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/base/node-serviceaccount.yaml
  hack/e2e/run.sh
  hack/eksctl-patch.yaml
  hack/kops-patch-node.yaml
  hack/kops-patch.yaml
  hack/values_eksctl.yaml
  test/e2e/e2e.go
Labels: approved, lgtm, size/L, cncf-cla: yes

#1096 Set efs-plugin container security context to true
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  deploy/kubernetes/base/controller-deployment.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#712 Updating documentation and adding storage class
  examples/kubernetes/statefulset/specs/example.yaml
  examples/kubernetes/static_provisioning/README.md
  examples/kubernetes/static_provisioning/specs/claim.yaml
  examples/kubernetes/static_provisioning/specs/pv.yaml
  examples/kubernetes/static_provisioning/specs/storageclass.yaml
Labels: ok-to-test, approved, lgtm, lifecycle/rotten, size/S, cncf-cla: yes

#640 Allow more control of the name of the directory created by the Access Point under Dynamic Provisioning
  charts/aws-efs-csi-driver/values.yaml
  docs/README.md
  examples/kubernetes/dynamic_provisioning/README.md
  examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml
  go.mod
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/sanity_test.go
Labels: ok-to-test, approved, lgtm, size/XXL, cncf-cla: yes

#1103 Update reading/writing without interruption after pod restart e2e test
  Dockerfile
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/templates/node-serviceaccount.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/base/node-serviceaccount.yaml
  hack/e2e/run.sh
  hack/eksctl-patch.yaml
  hack/kops-patch-node.yaml
  hack/kops-patch.yaml
  hack/values_eksctl.yaml
  test/e2e/e2e.go
Labels: approved, lgtm, size/L, cncf-cla: yes

#1101 Set efs-plugin container security context to true
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  deploy/kubernetes/base/controller-deployment.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1105 Pre-release PR for v1.6.0
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/L, cncf-cla: yes

#1108 post-release PR for v1.6.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1109 post-release PR for v1.6.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1090 Remove EBS references, window from e2e test
  hack/e2e/README.md
  hack/e2e/ebs.sh
  hack/e2e/eksctl.sh
  hack/e2e/run.sh
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#850 Fix GID allocator
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/gid_allocator.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/sanity_test.go
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/PATENTS
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, cncf-cla: yes
