Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#951 Move python packages to location on sys.path
  Dockerfile
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#952 Move python packages to location on sys.path
  Dockerfile
Labels: approved, lgtm, size/XS, cncf-cla: yes

#954 Pre-release PR of v1.5.3
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#953 Pre-release PR of v1.5.3
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#956 Post-release PR of v1.5.3
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#955 Post-release PR of v1.5.3
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#964 Updated the example IAM policy
  docs/iam-policy-example.json
Labels: approved, lgtm, size/S, cncf-cla: yes

#967 Pre-release PR for v1.5.4
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#968 Pre-release PR for v1.5.4
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#969 Post-release PR for v1.5.4
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#970 Post-release PR for v1.5.4
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes
