Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-05, with the labels that each got.

#984 Updated the K8s packages to 1.22.16 to mitigate the CVE-2022-3294
  go.mod
  go.sum
  vendor/github.com/bits-and-blooms/bitset/.gitignore
  vendor/github.com/bits-and-blooms/bitset/.travis.yml
  vendor/github.com/bits-and-blooms/bitset/LICENSE
  vendor/github.com/bits-and-blooms/bitset/README.md
  vendor/github.com/bits-and-blooms/bitset/azure-pipelines.yml
  vendor/github.com/bits-and-blooms/bitset/bitset.go
  vendor/github.com/bits-and-blooms/bitset/popcnt.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_19.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_amd64.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_amd64.s
  vendor/github.com/bits-and-blooms/bitset/popcnt_generic.go
  vendor/github.com/bits-and-blooms/bitset/trailing_zeros_18.go
  vendor/github.com/bits-and-blooms/bitset/trailing_zeros_19.go
  vendor/github.com/opencontainers/selinux/LICENSE
  vendor/github.com/opencontainers/selinux/go-selinux/doc.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs_linux.go
  vendor/github.com/opencontainers/selinux/pkg/pwalk/README.md
  vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/apiserver/pkg/admission/audit.go
  vendor/k8s.io/apiserver/pkg/audit/union.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/clientcmd/auth_loaders.go
  vendor/k8s.io/client-go/tools/pager/pager.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/transport.go
  vendor/k8s.io/client-go/util/workqueue/queue.go
  vendor/k8s.io/component-base/metrics/options.go
  vendor/k8s.io/component-base/version/.gitattributes
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/kubernetes/pkg/api/v1/pod/util.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/events.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/proxy/util/utils.go
  vendor/k8s.io/kubernetes/pkg/util/selinux/doc.go
  vendor/k8s.io/kubernetes/pkg/util/selinux/selinux.go
  vendor/k8s.io/kubernetes/pkg/util/selinux/selinux_linux.go
  vendor/k8s.io/kubernetes/pkg/util/selinux/selinux_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/util/hostutil/fake_hostutil.go
  vendor/k8s.io/kubernetes/pkg/volume/util/hostutil/hostutil_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_linux.go
  vendor/k8s.io/kubernetes/test/e2e/framework/volume/fixtures.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/proto/client/client.pb.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/proto/client/client.proto
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#993 Bumped the side-cars version to the latest
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#996 Pre-release PR for v1.5.5
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#997 Pre-release PR for v1.5.5
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#999 Post-release PR for V1.5.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1000 Post-release PR for V1.5.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#981 Add ability to configure daemonset affinity
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#992 Upgraded golang to 1.20
  Dockerfile
  go.mod
  go.sum
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#1001 Added the SecurityContext for Driver
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: approved, size/M, lgtm, cncf-cla: yes

#1002 Add reminder to always update weaveworks when updating policy
  docs/README.md
  docs/iam-policy-example.json
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1004 Updating README on how to delete access point when deleting PVC
  examples/kubernetes/dynamic_provisioning/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#701 Adding ability to set volMetricsOptIn on Daemonset
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1006 Updated the README with information on mountOptions that can be provided while mounting.
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1009 Updated Side-cars to address pull back error in private manifest
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1011 Readme Updates
  docs/README.md
  docs/iam-policy-example.json
  examples/kubernetes/dynamic_provisioning/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1012 Updated Side-cars to address pull back error in private manifest
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1013 Pre-release PR of v1.5.6
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1015 Pre-release of v1.5.6
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1017 Post-release of v1.5.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1016 Post-release of v1.5.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1020 Bump the helm version to pick the latest side-car images.
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1021 Bump the helm version to pick the latest side-car images.
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes
