Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-11, with the labels that each got.

#1177 Updated the Security Contact list
  SECURITY_CONTACTS
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1168 Fix typo in installation with public manifest
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1180 Fixed Posixuser nil pointer dereference issue
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/gid_allocator.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#1186 Pre-release for v1.7.1
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1185 Pre-release for v1.7.1
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1189 Post-release PR for v1.7.1
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1188 Post-release PR for v1.7.1
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1192 Update Static Provisioning README.md on mounttargetip option
  examples/kubernetes/static_provisioning/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S, cncf-cla: yes

#1193 Updated the apiversion in storageclass.yaml
  examples/kubernetes/static_provisioning/specs/storageclass.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1182 allocate GIDs in increasing order
  pkg/driver/controller_test.go
  pkg/driver/gid_allocator.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#1199 make gid allocator work with cross account feature
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/gid_allocator.go
  pkg/driver/sanity_test.go
Labels: approved, lgtm, size/L, cncf-cla: yes
