Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-01, with the labels that each got.

#872 This PR adds a check to see if the "allocated gid" is the default Go …
  pkg/driver/controller.go
Labels: ok-to-test, size/XS, cncf-cla: yes

#873 PR for bumping side cars version and adds a check to see if the "allocated gid" is the default Go int value, and skips attempting to deallocate it if is so.
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  pkg/driver/controller.go
Labels: ok-to-test, size/M, cncf-cla: yes

#870 Pre-release for v1.4.9
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, size/XS, cncf-cla: yes

#871 Pre-release for v1.4.9
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, size/XS, cncf-cla: yes

#875 Post release v1.4.9
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#874 Post release v1.4.9
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#882 Update Release.md
  docs/Release.md
Labels: approved, cncf-cla: yes

#880 Update e2e testing readme
  test/e2e/README.md
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#883 Update README for Container Arguments efs-plugin of efs-csi-node daem…
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#884 Update README for Container Arguments efs-plugin of efs-csi-node daem…
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#890 Update bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, size/XS, cncf-cla: yes

#896 Update README for tags Arguments efs-plugin of efs-csi-node daemonset
  docs/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S, cncf-cla: yes

#894 Update README for tags Arguments efs-plugin of efs-csi-node daemonset
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes
