Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2023-02, with the labels that each got.

#904 Bump the side cars version to the latest and allowing the parameter hostNetwork
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#905 Bump the side cars version to the latest and allowing the parameter hostNetwork
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#910 Remove hostNetwork option from controller
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  deploy/kubernetes/base/controller-deployment.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#913 Remove hostNetwork option from controller
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  deploy/kubernetes/base/controller-deployment.yaml
Labels: approved, size/XS, cncf-cla: yes

#911 Pre release PR for v1.5.0
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#917 Pre-release PR for main branch - release v1.5.0
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#916 Post release v1.5.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#914 Post release v1.5.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#903 New image based on minimal EKS Distro images
  Dockerfile
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#918 README update
  docs/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S, cncf-cla: yes

#919 README update
  docs/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S, cncf-cla: yes

#921 Pre-release PR for release branch - release v1.5.1
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#920 Pre-release PR for main branch - release v1.5.1
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#923 Post-release v1.5.1
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#924 Post-release v1.5.1
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#927 Added notes for the DNS resolving issue
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#928 Added notes for the DNS resolving issue
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#929 Added a link which references the file on how to add the IAM policy to DNS issue
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#930 Added a link which references the file to on how to add the policy.
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#740 feat(node/controller): allow to set updateStrategy
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#932 Updated the delete-access-point-root-dir argument in README
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#934 Adding mskanth972 to the owner list
  OWNERS
Labels: approved, lgtm, size/XS, cncf-cla: yes

#933 Updated the delete-access-point-root-dir argument in README
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#940 EFS CSI driver Minimal Image and support to define updateStrategy for controller deployment and node daemonset
  Dockerfile
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, size/M, lgtm, cncf-cla: yes

#942 Correctly passed the volume related arguments in the daemonset
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#941 Correctly passed the volume related arguments in daemonset
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#945 Updated the changelog
  CHANGELOG-1.x.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#938 Pre-release PR of v1.5.2
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#935 Updating README on how to retrieve mount target ip address when dns name cannot be resolved.
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#936 Updating README on how to retrieve mount target ip address when dns name cannot be resolved.
  docs/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#948 Post release - v1.5.2
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#949 Post release - v1.5.2
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes
