Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-09, with the labels that each got.

#1455 adding new regions' dns suffixes to watchdog
  Dockerfile
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1451 use protobuf content type instead of json for k8s client
  pkg/cloud/k8s_metadata.go
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1440 Update k8s dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#1461 V2.0.8 cherrypick
  Dockerfile
  charts/aws-efs-csi-driver/templates/csidriver.yaml
  charts/aws-efs-csi-driver/values.yaml
  go.mod
  go.sum
  pkg/cloud/k8s_metadata.go
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#1462 Pre-release PR for v2.0.8
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1463 Pre-release PR for v2.0.8
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1465 Post-release updates for release v2.0.8
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1464 Post-release updates for release v2.0.8
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes
