Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#1471 Add resources, topologySpreadConstraints and replicaCount to controller block
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#1474 Pre-release PR for v2.0.9
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1473 Pre-release PR for v2.0.9
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1478 Post-release updates for release v2.0.9
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1479 Post-release updates for release v2.0.9
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1475 Issue 1452: Update kubernetes to version 1.27.16 to patch CVE-2024-5321
  go.mod
  vendor/modules.txt
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1484 Bump side-cars to the latest
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1485 Update CodeQL workflow to v2
  .github/workflows/codeql-analysis.yml
Labels: approved, size/XS, cncf-cla: yes

#1486 Cherrypick PRs for the release v2.1.0
  .github/workflows/codeql-analysis.yml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  go.mod
  vendor/modules.txt
Labels: approved, size/M, cncf-cla: yes

#1487 Pre-release PR for v2.1.0
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#1488 Pre-release PR for v2.1.0
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#1490 Post-release PR for v2.1.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1489 Post-release PR for v2.1.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes
