Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#1496 Adds anti-affinity for incompatible compute types
  charts/aws-efs-csi-driver/values.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1480 chore: update Python base images to newer versions
  Dockerfile
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1469 feat: add portRangeUpperBound to be exposed in the helm chart
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  pkg/driver/efs_watch_dog.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1508 Add permissions to all GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/container-image.yaml
  .github/workflows/helm-chart-release.yaml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1404 Add Pod Disruption Budget and configurable deployment name
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-pdb.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, size/M, lgtm, cncf-cla: yes

#1507 Fix: Volume delete failed with static provisioning (#1207)
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: ok-to-test, approved, size/L, cncf-cla: yes

#1512 Fix: Adding new argument for csi provisioner
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
Labels: approved, size/XS, cncf-cla: yes
