Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-03, with the labels that each got.

#1281 Templatizing priotityClassName, hostNetwork, and additionalLabels in node-daemonset.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1288 Revert "Templatizing priotityClassName, hostNetwork, and additionalLabels in node-daemonset.yaml"
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1289 Update EFS Utils Restoration to Overwrite Certificates
  pkg/driver/efs_watch_dog.go
Labels: approved, size/XS, cncf-cla: yes

#1292 Add static & dynamic provisioning options for using efs-utils crossac…
  examples/kubernetes/cross_account_mount/README.md
  examples/kubernetes/cross_account_mount/specs/claim.yaml
  examples/kubernetes/cross_account_mount/specs/pod-static-prov.yaml
  examples/kubernetes/cross_account_mount/specs/pv.yaml
  examples/kubernetes/cross_account_mount/specs/storageclass-static-prov.yaml
  pkg/driver/controller.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#1293 Add unit tests for cross account dns feature
  pkg/driver/controller_test.go
  pkg/driver/node_test.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1295 Pre-release PR for v1.7.7
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1296 Pre-release PR for v1.7.7
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1300 Post-release PR for v1.7.7
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes
