Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-06, with the labels that each got.

#1364 Fix efs-proxy Zombie processes
  pkg/driver/reaper.go
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1366 Fix test file paths after dependency upgrades.
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#1367 Cherry pick + Pre-release for v2.0.4
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
  pkg/driver/controller.go
  pkg/driver/identity.go
  pkg/driver/node.go
  pkg/driver/reaper.go
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
Labels: approved, lgtm, size/L, cncf-cla: yes

#1368 Pre-release PR for v2.0.4
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1370 Post release PRs for v2.0.4
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1369 Post release PRs for v2.0.4
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1287 make sure the startup taint will eventually being removed after efs driver ready
  pkg/driver/driver.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#1075 docs(static_provisioning): add a note that don't proceed to the next step until pv `STATUS` is `Bound`
  examples/kubernetes/static_provisioning/README.md
Labels: ok-to-test, approved, lgtm, lifecycle/rotten, size/S, cncf-cla: yes

#1381 Add Pod Identity documentation in README
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1387 Bump Side-cars and add Patch Verbs
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/M, lgtm, cncf-cla: yes

#1392 Pre-release PR for v2.0.5
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S, cncf-cla: yes

#1391 Pre-release PR for v2.0.5
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1393 Post Release PR for v2.0.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1395 Post release PRs for v2.0.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1394 Add additionalLabels to node-daemonset
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes
