Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-08, with the labels that each got.

#1427 Update Go Version
  Dockerfile
  go.mod
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1429 Update Go Version
  Dockerfile
  go.mod
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1431 Pre-release PR for v2.0.7
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1430 Pre-release PR for v2.0.7
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1432 Post-release PR for v2.0.7
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1433 Post-release PR for v2.0.7
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1434 Support node.kubeletPath helm chart value
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes
