Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#1217 GIDs are not allocated correctly above certain volume threshold
  pkg/cloud/cloud.go
  pkg/driver/controller_test.go
  pkg/driver/gid_allocator.go
Labels: approved, size/M, lgtm, cncf-cla: yes

#1226 Reduce calls to EFS API
  pkg/cloud/cloud.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/gid_allocator.go
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#1230 Pre-release PR for v1.7.3
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1231 Pre-release PR for v1.7.3
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1234 Post-release PR for v1.7.3
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1235 Post-release PR for v1.7.3
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1238 Update EFS CSI Driver taint feature version info in docs
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1239 Update EFS CSI Driver taint feature version info in docs
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1196 Adding APA and FFZ regions to watchdog config template
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1246 Bump the side-cars to the latest to mitigate the CVEs
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1247 Bump the side-cars to the latest to mitigate the CVEs
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1248 pre-release PR for v1.7.4
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#1250 pre-release PR for V1.7.4
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#1251 post-release PR for v1.7.4
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1195 Added Fargate support in the EFS CSI Controller
  pkg/cloud/k8s_metadata.go
  pkg/cloud/k8s_metadata_test.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1259 Add note on memory usage for vol-metrics-opt-in in README
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1258 Add note on memory usage for vol-metrics-opt-in in README
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes
