Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-05, with the labels that each got.

#1334 Update the CHANGELOG link to point to latest file.
  .github/workflows/release.yaml
Labels: approved, size/XS, cncf-cla: yes

#1337 Pre-release PR for v2.0.2
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#1338 Pre-release PR for v2.0.2
  .github/workflows/release.yaml
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#1339 Post-release PRs for v2.0.2
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1340 Post-release PRs for v2.0.2
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1345 Update troubleshooting instructions to specify pod for debugging steps.
  troubleshooting/README.md
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1165 Expose env, volume, and volume mounts in helm chart for the efs controller and deamonset
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1358 pre-release PR for v2.0.3
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1362 post-release PRs for v2.0.3
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes
