Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-12, with the labels that each got.

#1376 Add `metadata.namespace` to chart templates
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/templates/node-serviceaccount.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1517 Pre-release PR for v2.1.1
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S, cncf-cla: yes

#1518 Pre-release PR for v2.1.1
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S, cncf-cla: yes

#1521 Post-release PR for release v2.1.1
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1522 Post-release PR for release v2.1.1
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1527 Pre-release PR for v2.1.2
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1528 Pre-release PR for v2.1.2
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1529 Update OWNERS
  OWNERS
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1532 Modify delete access point root directory logic to only remove temporary directory if empty
  pkg/driver/controller.go
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1539 Update remaining documentation and efs-csi-driver version tags as part of post-release PR for release v2.1.2
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1538 Update remaining documentation and efs-csi-driver version tags as part of post-release PR for release v2.1.2
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1540 Fix typo in kustomization tag
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1541 Fix typo in kustomization tag
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1543 Bump chart version
  charts/aws-efs-csi-driver/Chart.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1542 Bump chart version
  charts/aws-efs-csi-driver/Chart.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1545 Release 2.1.3 cherry pick
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  cmd/main.go
  docs/README.md
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/retry_manager.go
  pkg/cloud/retry_manager_test.go
  pkg/driver/controller.go
  pkg/driver/driver.go
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#1548 Pre-release PR for v2.1.3 (documentation and changelog)
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1550 Post release PR for v2.1.3
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1549 Post release PR for v2.1.3
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes
