Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-07, with the labels that each got.

#1400 Update statefulset example
  examples/kubernetes/statefulset/specs/example.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1414 Updated the docker file to install the latest version of Rust.
  Dockerfile
Labels: approved, size/XS, cncf-cla: yes

#1233 Refactor re-use Access Point
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/mocks/mock_cloud.go
Labels: ok-to-test, approved, lgtm, size/XL, lifecycle/stale, cncf-cla: yes

#1416 Pre-release PR for v2.0.6
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1417 Pre-release PR for v2.0.6
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1419 post-release PR for v2.0.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1418 post-release PR for v2.0.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes
