Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-02, with the labels that each got.

#1256 Allow controller SA to describe Secrets - fixes cross account dynamic provisioning
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  examples/kubernetes/cross_account_mount/iam-policy-examples/describe-mount-target-example.json
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#1263 Cherry picks for the New release v1.7.5
  charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  examples/kubernetes/cross_account_mount/iam-policy-examples/describe-mount-target-example.json
  pkg/cloud/k8s_metadata.go
  pkg/cloud/k8s_metadata_test.go
Labels: approved, size/L, cncf-cla: yes

#1264 Pre-release PR for v1.7.5
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/S, cncf-cla: yes

#1266 Post-release PR for v1.7.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1267 Post-release PR for v1.7.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1272 Disable efs-utils version check
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1152 Additional Controller Deployment features
  charts/aws-efs-csi-driver/templates/controller-deployment.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#1277 pre-release PR for v1.7.6
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1276 pre-release PR for v1.7.6
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1278 Cherry-pick for new release v1.7.6
  pkg/driver/controller.go
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS, cncf-cla: yes

#1279 Post-release PR for v1.7.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1280 Post-release PR for v1.7.6
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S, cncf-cla: yes
