Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2024-04, with the labels that each got.

#1302 Bump SIDECARS to the latest
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1303 Update test file manifest paths for e2e tests
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#1306 Install Rust and Cargo for building efs-utils v2.0.0
  Dockerfile
  test/e2e/e2e.go
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1304 Add script & instructions for in-place upgrade test.
  test/e2e/README.md
  test/e2e/upgrade_driver_version.sh
Labels: approved, lgtm, size/L, cncf-cla: yes

#1308 Update go-restful dependency
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/compress.go
  vendor/github.com/emicklei/go-restful/v3/constants.go
  vendor/github.com/emicklei/go-restful/v3/entity_accessors.go
  vendor/github.com/emicklei/go-restful/v3/json.go
  vendor/github.com/emicklei/go-restful/v3/jsoniter.go
  vendor/github.com/emicklei/go-restful/v3/jsr311.go
  vendor/github.com/emicklei/go-restful/v3/request.go
  vendor/github.com/emicklei/go-restful/v3/response.go
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/modules.txt
Labels: ok-to-test, approved, lgtm, size/L, cncf-cla: yes

#1313 Cherrypick PRs
  Dockerfile
  go.mod
  go.sum
  test/e2e/README.md
  test/e2e/e2e.go
  test/e2e/upgrade_driver_version.sh
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/compress.go
  vendor/github.com/emicklei/go-restful/v3/constants.go
  vendor/github.com/emicklei/go-restful/v3/entity_accessors.go
  vendor/github.com/emicklei/go-restful/v3/json.go
  vendor/github.com/emicklei/go-restful/v3/jsoniter.go
  vendor/github.com/emicklei/go-restful/v3/jsr311.go
  vendor/github.com/emicklei/go-restful/v3/request.go
  vendor/github.com/emicklei/go-restful/v3/response.go
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
  vendor/modules.txt
Labels: approved, size/L, cncf-cla: yes

#1312 Pre-release PRs for v2.0.0
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/M, cncf-cla: yes

#1314 Pre-release PRs for v2.0.0
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/M, cncf-cla: yes

#1316 Post-release PR for v2.0.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1315 Post-release PR for v2.0.0
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1317 Readme update
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1318 README Update
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1305 Templatize priorityClassName and additional labels
  charts/aws-efs-csi-driver/templates/node-daemonset.yaml
  charts/aws-efs-csi-driver/values.yaml
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1322 Pre-release PR for v2.0.1
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1321 Pre-release PR for v2.0.1
  CHANGELOG-1.x.md
  Makefile
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1324 Post-release PR for v2.0.1 and also changed the Default image from do…
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1323 Post-release PR for v2.0.1 and also changed the Default image from do…
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#1327 Update CHANGELOG to include 2.x for newer versions.
  CHANGELOG-1.x.md
  CHANGELOG-2.x.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#1328 Update CHANGELOG to include 2.x for newer versions.
  CHANGELOG-1.x.md
  CHANGELOG-2.x.md
Labels: approved, size/S, cncf-cla: yes

#1332 Update the Helm configuration to use Public ECR image as default rather…
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes

#1333 Update the Helm configuration to use Public ECR image default rather…
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, size/S, cncf-cla: yes
