Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#1554 docs: AAdd information about the incorporation of efs-utils v2.X.X in EFS CSI driver version 2.X.X.
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1552 Fix CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#1559 Revert to stunnel5
  Dockerfile
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1563 Update docs and Makefile for release 2.1.4
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1565 Update docs and Makefile for release 2.1.4
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1567 Post release 2.1.4
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1568 Post release 2.1.4
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1569 Upgrade python distro and create symlink to stunnel5
  Dockerfile
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes
