Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2025-02, with the labels that each got.

#1578 Fix CVE-2024-45338
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: kind/bug, ok-to-test, approved, lgtm, size/XXL, cncf-cla: yes

#1577 Pre-release PR for v2.1.5
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1579 Merge pull request #1577 from thakurmi/V2.1.5
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1580 Merge pull request #1569 from dankova22/stunnel-fix
  Dockerfile
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1581 Pre-Release 2.1.5
  CHANGELOG-2.x.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1582 Pre-release PR for v2.1.5 Part 2
  CHANGELOG-2.x.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1583 Post Release 2.1.5
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1584 Merge pull request #1583 from thakurmi/master
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1585 Remove libwrap=no from stunnel config on startup for newer stunnel co…
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#1586 Remove libwrap=no from stunnel config on startup for newer stunnel co…
  pkg/driver/efs_watch_dog.go
  pkg/driver/efs_watch_dog_test.go
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#1587 Pre release PR for 2.1.6
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1588 Pre release PR for 2.1.6
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1595 Add dankova22 to approvers
  OWNERS
Labels: ok-to-test, approved, lgtm, do-not-merge/invalid-owners-file, size/XS, cncf-cla: yes

#1596 Updating sidecar versions
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes
