Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#1599 Clarifying Note when uninstalling CSI driver
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1592 Volume create delete hardening
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/lock_manager.go
  pkg/driver/mocks/mock_mount.go
  pkg/driver/mounter.go
  pkg/driver/sanity_test.go
Labels: ok-to-test, approved, lgtm, size/XXL, cncf-cla: yes

#1604 Pre release PR for 2.1.7
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1605 Pre release PR for 2.1.7
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1607 Post release PR 2.1.7
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1608 Post release PR 2.1.7
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes
