Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2025-05, with the labels that each got.

#1619 Fix OpenSSL version mismatch
  Dockerfile
Labels: ok-to-test, approved, size/XS, cncf-cla: yes

#1618 fix centos image in pod config examples
  examples/kubernetes/access_points/specs/example.yaml
  examples/kubernetes/cross_account_mount/specs/pod-static-prov.yaml
  examples/kubernetes/cross_account_mount/specs/pod.yaml
  examples/kubernetes/dynamic_provisioning/specs/pod.yaml
  examples/kubernetes/encryption_in_transit/specs/pod.yaml
  examples/kubernetes/static_provisioning/specs/pod.yaml
  examples/kubernetes/volume_path/specs/example.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1621 Remove unused workflow that publishes images to dockerhub
  .github/workflows/container-image.yaml
Labels: ok-to-test, approved, size/M, lgtm, cncf-cla: yes

#1623 Release 2.1.8 cherry pick
  .github/workflows/container-image.yaml
  Dockerfile
  examples/kubernetes/access_points/specs/example.yaml
  examples/kubernetes/cross_account_mount/specs/pod-static-prov.yaml
  examples/kubernetes/cross_account_mount/specs/pod.yaml
  examples/kubernetes/dynamic_provisioning/specs/pod.yaml
  examples/kubernetes/encryption_in_transit/specs/pod.yaml
  examples/kubernetes/static_provisioning/specs/pod.yaml
  examples/kubernetes/volume_path/specs/example.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: ok-to-test, lgtm, size/L, cncf-cla: yes

#1622 Pre release for v2.1.8
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1626 Post release PR for release v2.1.8
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/S, cncf-cla: yes

#1627 Post release PR for release v2.1.8
  charts/aws-efs-csi-driver/CHANGELOG.md
  charts/aws-efs-csi-driver/Chart.yaml
  charts/aws-efs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: ok-to-test, lgtm, size/S, cncf-cla: yes
