Repository kubernetes-sigs/aws-efs-csi-driver, pull requests merged in 2025-06, with the labels that each got.

#1644 Update helm install FIPS docs capitalization to FIPS
  docs/README.md
Labels: approved, size/XS, cncf-cla: yes

#1638 openssl version mismatch fix
  Dockerfile
  Makefile
Labels: ok-to-test, approved, lgtm, size/XS, cncf-cla: yes

#1655 Pre-release PR 2.1.9 release
  CHANGELOG-2.x.md
  Makefile
  docs/README.md
Labels: ok-to-test, size/S, cncf-cla: yes
